config/routes.rb
Rails.application.routes.draw do
  root to: "chat_teams#index"

  resources :users, only: [:edit, :update, :destroy, :index, :show]
  post 'login' => "users#login", as: :login
  delete 'logout' => "users#logout", as: :logout

  resources :chat_teams, except: [:destroy]
  post 'chat_teams/:id/chat' => "chat_teams#chat"

end

app/models/chat_log.rb
class ChatLog < ActiveRecord::Base

  belongs_to :user

  validates :message, presence: true
end

app/models/chat_team.rb
class ChatTeam < ActiveRecord::Base

  belongs_to :owner, :foreign_key => :user_id, :class_name => "User"

  has_many :chat_logs, dependent: :destroy
  has_many :user_chat_teams, dependent: :destroy
  has_many :users, through: :user_chat_teams  

  validates :name, presence: true
  validates :users, presence: true

  before_create :add_owner

  def add_owner
    self.users << owner
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :chat_logs, dependent: :destroy
  has_many :user_chat_teams, dependent: :destroy
  has_many :chat_teams, through: :user_chat_teams

  validates :name, presence: true

end

app/models/user_chat_team.rb
class UserChatTeam < ActiveRecord::Base

  belongs_to :user
  belongs_to :chat_team

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logined?, :current_user

  protected

  def must_login
    unless logined?
      flash[:error] = "请先登录"
      redirect_to root_path
      return 
    end
  end

  def logined?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end

end

app/controllers/chat_logs_controller.rb
class ChatLogsController < ApplicationController
  before_action :set_chat_log, only: [:show, :edit, :update, :destroy]

  # GET /chat_logs
  # GET /chat_logs.json
  def index
    @chat_logs = ChatLog.all
  end

  # GET /chat_logs/1
  # GET /chat_logs/1.json
  def show
  end

  # GET /chat_logs/new
  def new
    @chat_log = ChatLog.new
  end

  # GET /chat_logs/1/edit
  def edit
  end

  # POST /chat_logs
  # POST /chat_logs.json
  def create
    @chat_log = ChatLog.new(chat_log_params)

    respond_to do |format|
      if @chat_log.save
        format.html { redirect_to @chat_log, notice: 'Chat log was successfully created.' }
        format.json { render :show, status: :created, location: @chat_log }
      else
        format.html { render :new }
        format.json { render json: @chat_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_logs/1
  # PATCH/PUT /chat_logs/1.json
  def update
    respond_to do |format|
      if @chat_log.update(chat_log_params)
        format.html { redirect_to @chat_log, notice: 'Chat log was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_log }
      else
        format.html { render :edit }
        format.json { render json: @chat_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_logs/1
  # DELETE /chat_logs/1.json
  def destroy
    @chat_log.destroy
    respond_to do |format|
      format.html { redirect_to chat_logs_url, notice: 'Chat log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_log
      @chat_log = ChatLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_log_params
      params.require(:chat_log).permit(:message)
    end
end

app/controllers/chat_teams_controller.rb
class ChatTeamsController < ApplicationController
  before_action :must_login, except: :index
  before_action :set_chat_team, only: [:show, :edit, :update, :destroy, :chat]

  def chat
    @chat_team.chat_logs.create(params.require(:chat_log).permit(:message))
    redirect_to @chat_team
  end

  def index
    @chat_teams = ChatTeam.all
  end

  def show
    @chat_logs = ChatLog.all
  end

  def new
    @chat_team = ChatTeam.new
    @users = User.where("users.id <> ?", current_user.id)
  end

  def edit
    @users = User.all
  end

  def create
    @chat_team = ChatTeam.new(chat_team_params)
    @chat_team.user_id = current_user.id
    @chat_team.users = User.where("id in (?)", params[:user_id])

    respond_to do |format|
      if @chat_team.valid?
        @chat_team.save!
        format.html { redirect_to chat_teams_url, notice: 'Chat team was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @chat_team.attributes = chat_team_params
    @chat_team.users = User.where("id in (?)", params[:user_id])

    respond_to do |format|
      if @chat_team.valid?
        @chat_team.save!
        format.html { redirect_to chat_teams_url, notice: 'Chat team was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_team
      @chat_team = ChatTeam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_team_params
      params.require(:chat_team).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    unless user = User.find_by(name: params[:user][:name])
      user = User.new(user_params)
      unless user.save
        flash[:error] = user.errors.full_messages.first
        redirect_to root_path
        return
      end
    end

    session[:user_id] = user.id

    redirect_to root_path
  end

  def logout
    session[:user_id] = nil

    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  ALERT_TYPES = [:danger, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type.to_s == :notice.to_s
      type = :danger   if type.to_s == :alert.to_s || type.to_s == :error.to_s
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end  

end

app/helpers/chat_logs_helper.rb
module ChatLogsHelper
end

app/helpers/chat_teams_helper.rb
module ChatTeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_teams/_form.html.haml
= form_for @chat_team, role: "form" do |f|
  - if @chat_team.errors.any?
    = render "layout/common/errors", errors: @chat_team.errors
    #error_explanation
      %h2= "#{pluralize(@chat_team.errors.count, "error")} prohibited this chat_team from being saved:"
      %ul
        - @chat_team.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    %label{ for: "chat_team_name" } 小组名称
    = f.text_field :name, class: "form-control"

  .form-group.members
    %label{ for: "chat_team_name" } 小组成员
    .checkbox
      %label
        = check_box_tag :owner, nil, true, disabled: true
        = current_user.name    
    - @users.each do |user|
      .checkbox
        %label
          = check_box_tag :user_id, user.id, @chat_team.users.include?(user)
          = user.name

  = submit_tag "提交", class: "btn btn-primary"
  = link_to "返回", chat_teams_path, class: "btn btn-default"        

app/views/chat_teams/edit.html.haml
.row
  .col-xs-4.col-xs-offset-4
    %h3 编辑聊天组
    = render 'form'

app/views/chat_teams/index.html.haml
.row
  .col-xs-4.col-xs-offset-4
    - if logined? 
      = link_to "创建聊天组", new_chat_team_path, class: "btn btn-primary"
    .panel.panel-default{style: "margin-top:20px;"}
      .panel-heading
        %h3.panel-title 聊天组列表
      %ul.list-group
        - @chat_teams.each do |chat_team|
          %li.list-group-item
            = link_to chat_team.name, chat_team
            - if logined? 
              .pull-right
                - if chat_team.user_id == current_user.id || current_user.admin?
                  %span.glyphico.glyphicon-edit 
                  = link_to "编辑", edit_chat_team_path(chat_team)

app/views/chat_teams/new.html.haml
.row
  .col-xs-4.col-xs-offset-4
    %h3 新建聊天组
    = render 'form'

app/views/chat_teams/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @chat_team.name
%p
  %b User:
  = @chat_team.user_id

#messages
  - @chat_logs.each do |log|
    %p= log.message

= form_for ChatLog.new, url: { action: :chat, id: @chat_team.id } do |f|
  = f.text_area :message
  = f.submit "发言"

= link_to 'Edit', edit_chat_team_path(@chat_team)
\|
= link_to 'Back', chat_teams_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ChatDemoBdd
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-static-top{:role => "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{:href => "/"} Chat Demo
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to "聊天组", chat_teams_path
          %ul.nav.navbar-nav.navbar-right
            - if logined?
              %li#user_name= link_to current_user.admin? ? current_user.name << "(管理员)" : current_user.name, edit_user_path(current_user)
              %li= link_to "登出", logout_path, method: :delete
            - else
              = form_for :user, url: login_path, method: :post, html: { class: "navbar-form"} do |f|
                .form-group
                  = f.text_field :name, class: "form-control", placeholder: "昵称"
                  = submit_tag "登录", class: "btn btn-primary" 
    .container
      = bootstrap_flash
    .container              
      = yield

app/views/layouts/common/_errors.html.haml
.alert.alert-warning.alert-dismissible{:role => "alert"}
  %button.close{"data-dismiss" => "alert", :type => "button"}
    %span{"aria-hidden" => "true"} &times;
    %span.sr-only Close
  %strong Warning!
    %ul
      - errors.full_messages.each do |msg|
        %li= msg

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :admin
    = f.check_box :admin
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Admin
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.admin
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Admin:
  = @user.admin

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path